name: app_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  shadcn_ui: ^0.25.1
  lucide_icons: ^0.257.0
  flex_color_scheme: ^8.2.0
  cached_network_image: ^3.4.1
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
